### ISSUE TITLE
Request: Disk Write Support

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/Atari800_MiSTer#12]
Hi! I try to write a little programs using MiSter and I can't write anything in disk, and there is no tape support.
would it be possible to implement write support to disk?

Thanks for your work!
P.D. In core documentation appears this:
 **Disks**
_A800: After mounting the disk, press F10 to boot. Some games don't like the Basic ROM. Keep F8(Option) pressed while pressing F10 to skip the Basic. Currently disks are read-only._

**Comment by sorgelig** [comment]
Actually core should support disk write. There are firmware functions for write. Although i'm not familiar with Atari 800 itself.
Make sure disk image is not read-only.

**Comment by lencio** [comment]
I try to write in an empty disk and I can't, in wiki site of core says "Current disk are read-only"
https://github.com/MiSTer-devel/Atari800_MiSTer

Thanks for reply!

**Comment by moralek** [comment]
If this is useful for you,
I created a clean altirra image (*. atr) with a DOS disk (2.5), formatting and then running the "INIT DOS FILES" option,
then in the MiSTer save with SAVE "D: TEST.BAS" and to load, LOAD "D: TEST.BAS",
this works for me

**Comment by lencio** [comment]
> If this is useful for you,
> I created a clean image (*. atr) in altirra with a DOS disk (2.5), formatting and then running the "INIT DOS FILES" option,
> then in the MiSTer save with SAVE "D: TEST.BAS" and to load, LOAD "D: TEST.BAS",
> this works for me

It's works! thanks for the info!
