### ISSUE TITLE
Controller Support: Atari 5200 Trak-ball

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Atari800_MiSTer#34]
The Atari 5200 trak-ball is the only other type of joystick supported by the 5200 console afaik. Here's a list of supported games: http://www.atarihq.com/5200/5200faq/02_07.html

Can this please be added to the 5200 core? :)

**Comment by KremlingKuthroat19** [comment]
After testing out some games such as Super Breakout and Kaboom it appears that the trackball is already natively supported to the left analog stick. It works great! I'm going to close this ticket :)

**Comment by Brianvgplayer** [comment]
What about Atari 800 Trak-Ball support in actual Trak-Ball mode? Only a handful of games support it, but it's definitely supported by Missile Command and one part of Final Legacy, Some ports of the 5200 Centipede to Atari 800 also support it. 

5200 only supports trackball through analog stick and not through mouse or trackball? Is there any way to toggle between Trak-Ball and paddle support for mouse or an actual trakball? While 5200 trackball is supported by analog stick, it's not the same as being able to use an actual trakball.
