### ISSUE TITLE
Virtual Disk Writes

### ISSUE THREAD

**Issue by argentini** [MiSTer-devel/Atari800_MiSTer#5]
Is there currently a way to write files to disk images or save a ram disk for later read/writes? If not, is this something planned for a future update?

**Comment by sorgelig** [comment]
Writing to disks are supported from the beginning. However formatting may not work, so you need to use a blank disk or disk with enough space.

**Comment by argentini** [comment]
Thanks for the info. I tried an app named atrcopy (a python 3 app installed via pip) and created a blank ss/sd ATR disk image, and it does work with file writes!
