### ISSUE TITLE
Problems loading CAR files with 20200509

### ISSUE THREAD

**Issue by Chris5523** [MiSTer-devel/Atari800_MiSTer#8]
After the latest update there seem to be RAM module depending issues loading CAR files. Space Harrier runs fine in the older versions for me, but in 20200509 it fails to run in 9 out of 10 tries and when it runs the graphics are often corrupt. A thread in the misterfpga forum shows several people also having problems with CAR files, while others can't reproduce the error.
I use a 128 MB XXSV module.

**Comment by sorgelig** [comment]
well, i don't see why it shouldn't work. It works for me, although i've tried other carts.
I guess you know that XXSV is not official SDRAM module and full compatibility isn't guaranteed.

**Comment by rittwage** [comment]
I have an original 32MB module and the same problem occurs. It doesn't load any cartridges anymore.

**Comment by rittwage** [comment]
I have the same issue - no CAR files run anymore. I have an original 32M module, so that is not likely the issue. It worked in previous versions of the core.

**Comment by sorgelig** [comment]
I need steps to reproduce the issue.

**Comment by sorgelig** [comment]
Do you start Atari 800 core from Menu core or from other core? Try to start from Menu core.

**Comment by Chris5523** [comment]
I start it from the Menu core.

**Comment by sorgelig** [comment]
May be someone wo has such issue has more than one SDRAM module and can try different modules?

**Comment by Chris5523** [comment]
Same behavior with my 32 MB SDRAM module. Works on old version of the core, doesn't work on new version of the core.

**Comment by rittwage** [comment]
I looked through the changes. Something with the T65 mods/hacks?  BAQuirk or Rdy_mod?

**Comment by mpryon** [comment]
I also have some fairly recent issues loading carts in the Atari 800 core, which led me here. After trying in two different MiSTer setups with a brand new, freshly setup SD card it seems to boil down to my SDRam modules. My old 32mb card no longer works with carts but my brand new 128mg works great.

0) Power up MiSTer
1) Select Atari800 core with keyboard
2) Load a cart file, any cart. I've not found one that works.

With OS-A or OS-B BIOS, I get a Select Cart Type menu (no matter which I choose, the core boots to Memo Pad.
Set to XL, it boots to the Atari Self Test screen.

In all cases, It's set to 64k RAM but I have tried other values with no change.

With the newer 128mb SDRam, everything works great with every ROM I've tried in all BIOS/RAM configs.

Both of my MiSTers work great with the new RAM and do not work with the older RAM.

I'm happy to try anything else and/or provide more details on the modules if it's help at all.

**Comment by sorgelig** [comment]
both old (32MB) and new (128MB) modules should work if they are both official. 
I will re-check with my modules.

**Comment by mpryon** [comment]
I'd not be surprised if the 32mb card is dodgy but I wouldn't even know how to confirm.
![PXL_20201031_160048595~2](https://user-images.githubusercontent.com/56358662/97803775-5e251b80-1c00-11eb-8a83-1afa741c8351.jpg)
![PXL_20201031_160035498~2](https://user-images.githubusercontent.com/56358662/97803777-5feedf00-1c00-11eb-8023-603f819d3ed6.jpg)

**Comment by sorgelig** [comment]
that's official one.

**Comment by mpryon** [comment]
Ahha. Thanks for the update. I've just rolled back the build of the Atari800 core (Atari800_20190927.rbf) and sure enough, as the OP says, carts seem to work perfectly with the 32MB Winbond board.

I update to the latest and it's broken again.

I've got another working rig anyway so I'll probably just leave it for now rather than buying another module.

Thanks again,
mikol

**Comment by lencio** [comment]
I can't run any CART with last version of core. I rolled back to Atari800_20190927.rbf and cat run any carts now.
I have 32MB card.

**Comment by lencio** [comment]
With today update (20201128), the CART support is working now!!! Thanks a lot!!!!

**Comment by preryon** [comment]
Yep, it appears to be working now on my Winbond 32mb RAM board as well as my Alliance 128mb board.
